# Generated by Django 3.2.8 on 2021-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 1), (-1, -1)], default=(1, 1), verbose_name='like'),
        ),
    ]
